lista/urls.py
from django.conf.urls import url
from . import views
from .views import *
from django.urls import path
from django.contrib.auth.decorators import login_required
app_name = 'lista'

urlpatterns = [

    path('listadol/',login_required(ListadoLista.as_view()), name = 'listadol'),
    path('crearl/',login_required(CrearLista.as_view()), name = 'crearl'),

]

sistema_votacion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
#import Inicio from lista.views
from sistema_votacion import views as app_views
from usuario.views import Login,logoutUsuario
from lista.views import Inicio
from votante.views import Inicio
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',login_required(Inicio.as_view()), name = 'index'),
    url(r'^error_image$', app_views.errorImg),
    url(r'^create_dataset$', app_views.create_dataset),
    url(r'^trainer$', app_views.trainer),
    url(r'^detect$', app_views.detect),
    url(r'^detect_image$', app_views.detectImage),
    path('votante/',include(('votante.urls','votante'))),
    path('lista/',include(('lista.urls','lista'))),
    path('logout/',login_required(logoutUsuario),name = 'logout'),
]

votante/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views
from .views import *
app_name = 'votante'

urlpatterns = [
    #path('voto/<int:id>/',login_required(voto.as_view()), name = 'voto'),
    path('crearv/',login_required(CrearVotante.as_view()), name = 'crearv'),
    #path('crearv/',views.CrearVotante, name = 'crearv'),
    path('listadov/',login_required(ListadoVotante.as_view()), name = 'listadov'),

    url(r'^voto/(?P<id>\d+)/$', views.voto, name='voto'),


]

votante/models.py
from __future__ import unicode_literals
from django.db import models

class Sexo(models.Model):
    id = models.AutoField(primary_key = True)
    nombre = models.CharField(max_length = 200, blank = False, null = False)
    estado = models.BooleanField('Estado', default = True)
    fecha_creacion = models.DateField('Fecha de creación', auto_now = True, auto_now_add = False)

    class Meta:
        verbose_name = 'Sexo'
        verbose_name_plural = 'Sexos'
        ordering = ['nombre']

    def __str__(self):
        return '%s' % (self.nombre)

class Votante(models.Model):
    id = models.AutoField(primary_key = True)
    cedula = models.IntegerField(unique=True, blank = False, null= False)
    nombre = models.CharField(max_length = 200, blank = False, null = False)
    apellido = models.CharField(max_length = 220, blank = False, null = False)
    telefono = models.CharField(max_length = 100, blank = False, null = False)
    direccion = models.TextField(max_length = 220, blank = False, null = False)
    correo = models.CharField(max_length = 220,blank = False,null = False)
    sexo_id = models.ManyToManyField(Sexo)
    estado = models.BooleanField('Estado', default = True)
    fecha_creacion = models.DateField('Fecha de creación', auto_now = True, auto_now_add = False)

    class Meta:
        verbose_name = 'Votante'
        verbose_name_plural = 'Votantes'
        ordering = ['apellido']

    def __str__(self):
        return '%s %s' % (self.apellido, self.nombre)

votante/forms.py
from django import forms
from .models import Sexo,Votante
from django.core.files import File

#@admin.register(Sexo)
class SexoForm(forms.ModelForm):
    class Meta:
        model = Sexo
        fields = ['nombre']
        label = {
            'nombre':'nombre',
        }
        widgets = {
            'nombre': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese sexo'
                }
            )
        }

class VotanteForm(forms.ModelForm):
    class Meta:
        model = Votante
        fields = ('cedula','nombre','apellido','telefono','direccion','correo','sexo_id')
        label = {
            'cedula':'cédula del votante',
            'nombre':'nombre del votante',
            'apellido':'apellido del votante',
            'telefono':'teléfono del votante',
            'direccion':'dirección del votante',
            'correo':'correo del votante',
            'sexo_id': 'sexo del votante',
            #'foto': 'f',
        }
        widgets = {
            'cedula': forms.NumberInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese cédula del votante',
                    'type': 'number',
                    'id': 'cédula'
                }
            ),
            'nombre': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese nombre del votante',
                    'id': 'nombre'
                }
            ),
            'apellido': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese apellido del votante',
                    'id':'apellido'
                }
            ),
            'telefono': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese teléfono del votante',
                    'id':'telefono'
                }
            ),
            'direccion': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Ingrese dirección del votante',
                    'id':'direccion'
                }
            ),
            'correo': forms.EmailInput(
                attrs = {
                    'class': 'form-control',
                    'type': 'email',
                    'placeholder': 'ejemplo@ejemplo.com',
                    'id':'correo'
                }
            ),
            'sexo_id': forms.Select(
                attrs = {
                    'class':'form-control',
                    'id':'sexo'
                }
            )
        }

    # def __init__(self, *args, **kwargs):
    #     super(VotanteForm, self).__init__(*args, **kwargs)
    #     for field in iter(self.fields):
    #         if field <> 'estado':
    #             self.fields[field].widget.attrs.update({
    #                 'class': 'form-control'
    #             })

votante/views.py
from __future__ import unicode_literals 
from .models import Votante
from django.views.generic import View,TemplateView,ListView,UpdateView,CreateView,DeleteView
from django.shortcuts import render,redirect
from django.core.exceptions import ObjectDoesNotExist
from .forms import VotanteForm
from django.urls import reverse_lazy
from django.http import HttpResponse
# Create your views here.

class Inicio(TemplateView):
    template_name = 'index.html'


class ListadoVotante(ListView):
    model = Votante
    template_name = 'listadov.html'
    context_object_name = 'votantes'
    queryset = Votante.objects.filter(estado = True)

class ActualizarVotante(UpdateView):
    model = Votante
    form_class = VotanteForm
    template_name = 'editarv.html'
    success_url = reverse_lazy('listadov')

class CrearVotante(CreateView):
    model = Votante
    form_class = VotanteForm
    template_name = 'crearv.html'
    success_url = reverse_lazy('votante:listadov')

class EliminarVotante(DeleteView):
    model = Votante

    def post(self,request,pk,*args,**kwargs):
        object = Votante.objects.get(id = pk)
        object.estado = False
        object.save()
        return redirect('listadov')

def voto(request, id):
    votante = Votante.objects.get(id=id)
    context = {
        'votante' : votante
    }
    return render(request, 'voto.html', context)

templates/confirmacion.html
{% extends 'layout.html' %}

{% block titulo %}
  elecciones 2020 | Esta seguro del voto
{% endblock titulo %}

{% block body %}

<form method="post">
  {% csrf_token %}
  <p><strong>¿Desea enviar el voto {{ object }}?</strong></p>
  <button type="submit" class="btn btn-danger" href="/">Confirmar</button>
</form>

{% endblock body %}

templates/crearl.html
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h2 class="modal-title">Creacion de Lista</h2>
      <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <form action="{% url 'crearl' %}" method="POST">
      {% csrf_token %}
      <div class="modal-body">
        {{ form.as_p }}
      </div>
      <div class="modal-footer">
        <button class="btn btn-danger" type="button" data-dismiss="modal">Cancelar</button>
        <button class="btn btn-primary" type="submit">Confirmar</button>
      </div>
    </form>
  </div>
</div>

templates/crearv.html
{% extends 'index.html' %}


{% block content %}

<div class="container" >
<form method="POST">
  {% csrf_token %}

  {% if error %}
    <h2>{{ error }}</h2>
  {% else %}
      <div class="card">
          <div class="card-header">
              <strong>Formulario de Registro</strong>
          </div>
          <div class="card-body card-block">
              <form action="#" method="post" enctype="multipart/form-data" class="form-horizontal">
                  <div class="row form-group">
                    <div class="col col-md-3">{{ form.cedula.label }}</div>
                    <div class="col-12 col-md-9">{{ form.cedula }}</div>
                  </div>
                  <div class="row form-group">
                      <div class="col col-md-3">{{ form.nombre.label }}</div>
                      <div class="col-12 col-md-9">{{ form.nombre }}</div>
                  </div>
                  <div class="row form-group">
                      <div class="col col-md-3">{{ form.apellido.label }}</div>
                      <div class="col-12 col-md-9">{{ form.apellido }}</div>
                  </div>
                  <div class="row form-group">
                      <div class="col col-md-3">{{ form.telefono.label }}</div>
                      <div class="col-12 col-md-9">{{ form.telefono }}</div>
                  </div>
                  <div class="row form-group">
                      <div class="col col-md-3">{{ form.direccion.label }}</div>
                      <div class="col-12 col-md-9">{{ form.direccion }}</div>
                  </div>
                  <div class="row form-group">
                      <div class="col col-md-3">{{ form.correo.label }}</div>
                      <div class="col-12 col-md-9">{{ form.correo }}</div>
                      <!-- <input id="emailAddress" type="email" size="64" maxLength="64" required
          placeholder="username@beststartupever.com" pattern="tigrerokaren@gmail.com"
          title="Please provide only a Best Startup Ever corporate email address">{{ form.correo }} -->
          <!-- <input id="emailAddress" type="email" placeholder="user@example.gov"
       list="defaultEmails" size="64" maxlength="256" multiple>
       <datalist id="defaultEmails">
         <option value="jbond007@mi6.defence.gov.uk">
         <option value="jbourne@unknown.net">
         <option value="nfury@shield.org">
         <option value="tony@starkindustries.com">
         <option value="hulk@grrrrrrrr.arg">
       </datalist> -->
                  </div>
                  <div class="row form-group">
                        <div class="col col-md-3">{{ form.sexo_id.label }}</div>
                        <div class="col-12 col-md-9">{{ form.sexo_id }}</div>
                    </div>

              </form>
              <div class="text-center">
                  <!-- <button type="submit" class="btn btn-primary">Registrar</button> -->
                  <input type="submit" class="btn btn-primary" name="submit" value="Guardar">
                  <button type="reset" class="btn btn-danger">Cancelar</button>
              </div>
          </div>

      </div>
  {% endif %}
</form>
<div class="col-md-12" style="margin-top:2em">
  <a href="/" class="btn btn-warning"><i class="fa fa-chevron-left" aria-hidden="true"></i> INICIO</a>
</div>
</div>


{% endblock %}

templates/error.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
<div class="container" style="height:88vh">
  <div style="padding-bottom: 2em;">
    <h1 class="text-center jumbotron">¡Huy! Algo salió mal!<i class="fa fa-frown-o" aria-hidden="true"></i>
</h1>
    <h3>Nuestra sugerencia</h3>
    <p><i class="fa fa-dot-circle-o" aria-hidden="true"></i>Asegúrese de que su imagen tenga una cara visible y clara sin obstrucciones e intente nuevamente. <i class="fa fa-smile-o" aria-hidden="true"></i></p>
  </div>
  <a href="/" class="btn btn-warning"><i class="fa fa-chevron-left" aria-hidden="true"></i> Volver </a>
</div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}

<div id="particles-js"></div>
<div class="container" >
  <div class="col-lg-12" style="background: rgba(0,0,0,0.6);margin-top:3em;margin-bottom:5em;padding-top:1em;padding-bottom:3em;color:#fff;border-radius:10px;-webkit-box-shadow: 2px 2px 15px 0px rgba(0, 3, 0, 0.7);
-moz-box-shadow:    2px 2px 15px 0px rgba(0, 3, 0, 0.7);
box-shadow:         2px 2px 15px 0px rgba(0, 3, 0, 0.7);">
<style>
  .user-area {
    float: right;
    padding-right: 0;
    position: relative;
    padding-left: 20px; }
    .user-area .user-menu {
      background: #fff;
      border: none;
      left: inherit !important;
      right: 0;
      top: 54px !important;
      margin: 0;
      max-width: 150px;
      padding: 5px 10px;
      position: absolute;
      width: 100%;
      z-index: 999;
      min-width: 150px;
      -webkit-box-shadow: 0 3px 12px rgba(0, 0, 0, 0.05);
              box-shadow: 0 3px 12px rgba(0, 0, 0, 0.05); }
      .user-area .user-menu .nav-link {
        color: #607d8b;
        display: block;
        font-size: 13px;
        line-height: 22px;
        padding: 5px 0; }
        .user-area .user-menu .nav-link > i {
          margin-right: 10px; }
    .user-area .user-avatar {
      float: right;
      width: 40px; }

    .user-area .user-info .name {
      color: #8c8c8c;
      font-size: 14px;
      position: relative;
      text-transform: uppercase; }
    .user-area .count {
      background: #d9534f;
      border-radius: 50%;
      color: #fff;
      font-family: 'Open Sans';
      font-size: 9px;
      font-weight: 700;
      float: right;
      height: 20px;
      width: 20px;
      line-height: 20px;
      text-align: center; }
    .user-area .dropdown-toggle {
      line-height: 55px;
      height: 55px;
      display: -webkit-box;
      display: -ms-flexbox;
      display: flex;
      -webkit-box-pack: center;
          -ms-flex-pack: center;
              justify-content: center;
      -webkit-box-align: center;
          -ms-flex-align: center;
              align-items: center; }
      .user-area .dropdown-toggle:after {
        display: none; }

</style>
    <div class="col-lg-12">
      <div class="top-right">
                <div class="header-menu">
                    <div class="user-area dropdown float-right">
                        <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="user-avatar rounded-circle" src="{% static 'images/admin.png' %}" alt="User Avatar">
                            <h6 class="text-center">{{ user.username | upper }}</h6>
                        </a>
                        <div class="user-menu dropdown-menu">
                            <a class="nav-link" href="#"><i class="fa fa- user"></i>Perfil</a>
                            <a class="nav-link" href="/admin/logout/"><i class="fa fa-power -off"></i>Logout</a>
                        </div>
                    </div>

                </div>
            </div>
      <h1 class="text-center section-title" style="margin-bottom:2em">VOTO ELECTRÓNICO MEDIANTE RECONOCIMIENTO FACIAL.</h1>
    </div>
    <style>
      h4{
        margin-bottom: 1.5em;
      }
      img{
        border-radius:50%;
        -webkit-transition: all 0.3s ease-in-out;
    -moz-transition: all 0.3s ease-in-out;
     transition: all 0.3s ease-in-out;
      }
      img:hover{
        -webkit-box-shadow: 2px 2px 21px 0px rgba(0, 3, 0, 0.91);
        -moz-box-shadow:    2px 2px 21px 0px rgba(0, 3, 0, 0.91);
        box-shadow:         2px 2px 21px 0px rgba(0, 3, 0, 0.91);
        border:2px solid #fff;
      }
      h3{
        margin-bottom: 1.3em;
      }
      a{
        color:inherit
      }
      a:hover{
        color:inherit;
        text-decoration: none;
      }
      .section-title:after {
        	content:' ';display:block;margin:0 auto;width:100px;margin-top: 6px;border:2px solid #d0d0d0;border-radius:4px;
        	-webkit-border-radius:4px;
        	-moz-border-radius:4px;
        	box-shadow:inset 0 1px 1px rgba(0, 0, 0, .05);
        	-webkit-box-shadow:inset 0 1px 1px rgba(0, 0, 0, .05);
        	-moz-box-shadow:inset 0 1px 1px rgba(0, 0, 0, .05);
          margin-bottom:1em;
        }
    </style>

    <div class="row">
      <div class="col-md-5" style="border-right: 2px solid;">
        <h3 class="text-center">REGISTRO</h3>
        <div class="col-md-6">
          <!-- <a href="/listadol"><img src="{% static 'img/list.png' %}" class="img-responsive" /></a> -->
          <a   href="{% url 'lista:listadol' %}"><img src="{% static 'img/list.png' %}" class="img-responsive" /></a>
          <h4 class="text-center">LISTAS</h4>
        </div>
        <div class="col-md-6">
          <a  target="_blank" href="{% url 'votante:crearv' %}" method="post"><img src="{% static 'img/votant.png' %}" class="img-responsive" /></a>
          <h4 class="text-center">VOTANTES</h4>
        </div>
      </div>
      <div class="col-md-7">
        <h3 class="text-center"> VOTO | RECONOMIENTO  </h3>
        <div class="col-md-4">
          <button type="button" style="background:transparent;border:none" data-toggle="modal" data-target="#myModal">
            <img src="{% static 'img/add.png' %}" class="img-responsive" />
          </button>
          <h4 class="text-center">REGISTRO RECONOCIMIENTO</h4>
        </div>
        <div class="col-md-4">
          <a href="/trainer"><img src="{% static 'img/trainer.png' %}" class="img-responsive" /></a>
          <h4 class="text-center">ENTRENAMIENTO</h4>
        </div>
        <div class="col-md-4">
          <a href="/detect"><img src="{% static 'img/webcam.png' %}" class="img-responsive" /></a>
          <h4 class="text-center">VOTO</h4>
        </div>
      </div>
    </div>
    <div class="low">
      <div class="col-md-7">

        <center><h3 class="text-center">********************************************** REPORTES **********************************************</h3></center>
        <div class="col-md-4">
          <a href="/reporte_candidato" target="_blank"><img src="{% static 'img/candidato.png' %}" class="img-responsive" /></a>
          <h4 class="text-center">Candidatos</h4>
        </div>
        <div class="col-md-4">
          <a href=""><img src="{% static 'img/lista.png' %}" class="img-responsive" /></a>
          <h4 class="text-center">Listas</h4>
        </div>
        <div class="col-md-4">
          <a href=""><img src="{% static 'img/votante.png' %}" class="img-responsive" /></a>
          <h4 class="text-center">Votantes</h4>
        </div>
        <div class="col-md-4">
          <a href=""><img src="{% static 'img/vo.png' %}" class="img-responsive" /></a>
          <h4 class="text-center">VOTO</h4>
        </div>
        <div class="col-md-4">
          <a href=""><img src="{% static 'img/rep_gana.png' %}" class="img-responsive" /></a>
          <h4 class="text-center">Ganador</h4>
        </div>
        </div>
      </div>

</div><!-- Container -->

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Ingrese una identificación única y espere la cámara web</h4>
      </div>
      <div class="modal-body">
        <ul>
          <li>Para mayor precisión, asegúrese de permanecer en la habitación con buenos rayos.</li>
          <li>Elimine cualquier tipo de accesorio de la cara.</li>
          <li>Asegúrese de que su cara esté claramente visible en la cámara.</li>
          <li>Asegúrate de que tu cabello no esté bloqueando la cara.</li>
          <li>Asegúrese de que no haya otras caras dentro del marco de la cámara.</li>
        </ul>
        <hr/>
        <form action="/create_dataset" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="inputId">*INGRESE SU ID ÚNICO*</label>
            <input type="text" class="form-control" name="userId" id="inputId" placeholder="REGISTRAR">
          </div>
          <button type="submit" class="btn btn-warning">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.jpg' %}" />
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'jquery.min.js' %}"></script>
    <link href="https://fonts.googleapis.com/css?family=Muli:400,600" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
  </head>

  <body>

    {% block content %}
    {% endblock %}

    {% block body %}
    {% endblock body %}
    <footer style="background-color: rgb(28, 28, 28);padding:2em 0;margin-top:1em;">
      <p class="text-center" style="margin-bottom:0;color:#fff">Creado por Karen Tigrero, Tesina.</p>
    </footer>
    <!-- Custom scripts for this template -->
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/particles.min.js' %}" ></script>
    <script src="{% static 'script.js' %}"></script>
  </body>

</html>

templates/listadol.html
{% extends 'layout.html' %}

{% load static %}
{% block titulo %}
Elecciones 2020 | Listado de Lista
{% endblock titulo %}

{% block content %}
<div>
  <button class="btn btn-primary" type="button" onclick="abrir_modal_creacion(lista:crearl)">Crear Lista</button>
</div>
{% if listas %}
<div class="card">

  <div class="card-header">
    <strong class="card-title">Listado de Listas</strong>
  </div>
  <div class="table-stats order-table ov-h">
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nombre</th>
          <th>Candidatos</th>
          <th>Propuesta</th>
          <th>Opciones</th>
        </tr>
      </thead>
      <tbody>
        {% for lista in listas %}
        <tr>
          <td>{{ lista.id }}</td>
          <td>{{ lista.nombre }}</td>
          <td>
            {% for candidato in lista.candidato_id.all %}
            <li>{{ candidato.nombre }}</li>
            {% endfor %}
          </td>
          <td>{{ lista.propuesta }}</td>
          <td>
            <a href="/lista/eliminarl/{{lista.id}}" class="btn btn-danger">Eliminar</a>
            <button onclick="abrir_modal_edicion('/lista/editarl/{{lista.id}}" class="btn btn-primary">Editar</button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% else %}
<h1>No existen listas registrados</h1>
{% endif %}

<div class="modal fade" id="creacion" role="dialog">

</div>

<div class="modal fade" id="edicion" role="dialog">

</div>

{% endblock content %}

{% block extrajs %}

<script type="text/javascript">
  var $ = jQuery.noConflict();
  function abrir_modal_edicion(url){
    $('#edicion').load(url, function (){
      $(this).modal('show');
    });
  }
  function abrir_modal_creacion(url){
    $('#creacion').load(url,function(){
      $(this).modal('show');
    });
  }
</script>
{% endblock extrajs %}

templates/listadov.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}

  {% if votantes %}
      <div class="card">
          <div class="card-header">
              <strong class="card-title">Listado de Candidatos</strong>
          </div>
          <div class="table-stats order-table ov-h">
              <table class="table">
                  <thead>
                      <tr>
                        <th>ID</th>
                        <th>Cédula</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Teléfono</th>
                        <th>Dirección</th>
                        <th>Correo</th>
                        <th>sexo</th>
                        <th>Opciones</th>
                      </tr>
                  </thead>
                  <tbody>
                    {% for votante in votantes %}
                      <tr>
                        <td>{{ votante.id }}</td>
                        <td>{{ votante.cedula}}</td>
                        <td>{{ votante.nombre }}</td>
                        <td>{{ votante.apellido }}</td>
                        <td>{{ votante.telefono }}</td>
                        <td>{{ votante.descripcion }}</td>
                        <td>{{ votante.correo }}</td>
                        <td>
                            {% for sexo in votante.sexo_id.all %}
                              <li>{{ sexo.nombre }}</li>
                            {% endfor %}
                        </td>
                        <td>
                          <!-- <a href="{% url 'lista:editar_candidato' candidato.id %}" class="btn btn-primary">Editar</a>
                          <a href="{% url 'lista:eliminar_candidato' candidato.id %}" class="btn btn-danger">Eliminar</a> -->
                        </td>
                      </tr>
                    {% endfor %}
                  </tbody>
              </table>
          </div>
      </div>
      {% else %}
        <h1>No existen votante registrados</h1>
      {% endif %}

{% endblock content %}

templates/reporte_candidato.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
{% if candidatos %}
    <title>CANDIDATOS</title>
  </head>
  <body>
    <center><h1>LIGA DEPORTIVA CANTONAL LA LIBERTAD</h1></center>
    <p>REPORTE DE CANDIDATOS</p>
    <table class="table">
  

    <div class="col-md-12" style="text-align:center">
      <h3 style="color:#d18f02"><b>{{candidato.id}}</b></h3>
      <h5><b>{{candidato.cedula}}</b></h5>
      <h5><b>Nombre: </b> {{candidato.nombre}} </h5>
      <h5><b>apellidos: </b> {{candidato.apellidos}} </h5>
      <h5><b>descripcion: </b> {{candidato.descripcion}} </h5>

    </div>
    </table>
  </body>
{% else %}
    <h1>No existen candidatos registrados</h1>
{% endif %}
</html>

templates/votante.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
<div class="container">
  <h1 class="jumbotron">Votante</h1>
  <ul>
    {% for votante in votantes %}
      <li><a href="/votantes/voto/{{votante.cedula}}">{{votante.nombre}} {{votante.apellido}}</a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}